apiVersion: v2
name: pds
description: A Helm chart for deploying an atproto Personal Data Server
type: application
version: 0.1.0
appVersion: "latest"
dependencies:
- name: postgresql
  version: ">= v12"
  repository: https://charts.bitnami.com/bitnami